### ISSUE TITLE
example wrongly returns 'Address INVALID' when it should return 'valid' on @'Linux Mint 18.3 Sylvia' node@v8.11.1

### ISSUE THREAD

**Issue by onslm** [ryanralph/altcoin-address#8]
Hello friends,
sorry, kind od newbie here, I don't have any idea how it can be debugged... But I'm pretty sure that the module doesn't work on my system.

I've tried altcoin-address both in myApp.js (i.e. node myApp.js in terminal) and also in plain Node's REPL - no matter what BTC address (I tried many valid and to be sure also many invalid addresses) I pass to validate function it always evaluates to false.

Here's an output from my console with evaluation of your "valid" example in Node's REPL:
```
➜  btc-sender-bot node 
> var altcoin = require('altcoin-address');
undefined
> var valid = altcoin.validate('1KFzzGtDdnq5hrwxXGjwVnKzRbvf8WVxck', 'bitcoin');
undefined
> if (valid) { console.log('This is a valid address');} else { console.log('Address INVALID'); } 
Address INVALID
undefined
> 
(To exit, press ^C again or type .exit)
```

Thanks in advance for any information ;)

Kind regards
onslm

**Comment by ryanralph** [comment]
Hi Ondrej,

This sounds to me like a problem with your local configuration. I'm not
really in a position to provide a great deal of support with this library.

Firstly can I just check that you've installed the module correctly via
"npm install altcoin-address"?

I have attached a dump of the steps I used to test that everything still
works on my own machine:

> In the next post, apparently email replies don't allow markdown

I hope this is of use in your debugging efforts. Please reply back if your
issue is resolved.

**Comment by ryanralph** [comment]
``` ~$ npm install altcoin-address
/home/ryanralph
└─┬ altcoin-address@1.0.2
  └── int@0.1.1

npm WARN enoent ENOENT: no such file or directory, open
'/home/ryanralph/package.json'
npm WARN ryanralph No description
npm WARN ryanralph No repository field.
npm WARN ryanralph No README data
npm WARN ryanralph No license field.
~$ nodejs
> var altcoin = require('altcoin-address')
undefined
> var valid = altcoin.validate('1KFzzGtDdnq5hrwxXGjwVnKzRbvf8WVxck',
'bitcoin');
undefined
> valid
true
```
